### ISSUE TITLE
Add Contact page/section in the website

### ISSUE THREAD

**Issue by muhafiz5814** [muhafiz5814/haji-flour-mill#18]
There is no contact page in site which can be used to contact the owner or the maintainers of the business.

**Comment by mohamedhesham221** [comment]
To clarify the Contact page/section requirement:

Do you have a specific design or layout in mind? (e.g., color scheme, typography, or style preferences)
Are there any examples of Contact pages you like or want to emulate?

**Comment by muhafiz5814** [comment]
@mohamedhesham221 color scheme should be same as in existing website that black and white, buttons blue.
at top there should be some information for users that it is a contact page for there queries and business improvement suggestions.
Below it there are two divisions, on left there should be a form to submit query and at right side there should be a google map window which locates to the physical business address.

### Example screenshot

![Contact page screenshot](https://github.com/user-attachments/assets/f6a5015b-18fd-4944-9090-07297291e866)

These are basic requirements for the UI.

**Comment by mohamedhesham221** [comment]
Oky , I am working on

**Comment by mohamedhesham221** [comment]
- Do you have a list of countries you’d like to include in the form?
- Do you want to include more inputs like email or telephone number?

**Comment by muhafiz5814** [comment]
> * Do you have a list of countries you’d like to include in the form?
> * Do you want to include more inputs like email or telephone number?

@mohamedhesham221 , Yeah, you can add input field of email, not telephone.
Instead of list of countries, add following local area cities as it's a local business:
- Talera, Bundi
- Keshoraipatan, Bundi
- Bundi
- Ladpura, Kota
- Kota

These can be updated later, it's good for now.
